"use client";

import { PieChart, TrendingUp, Handshake, Leaf, Map, Sprout } from "lucide-react";
import CountUpNumber from "@/components/CountUpNumber";
import Link from "next/link";
import Image from "next/image";

export default function Resources() {
    return (
        <div className="bg-[#FAF9F6] min-h-screen font-sans text-deep-forest selection:bg-kelp-green selection:text-white">

            {/* Contained Minimal Hero */}
            <section className="pt-8 px-4 sm:px-6 lg:px-8 max-w-[1400px] mx-auto">
                <div className="glass-card p-12 md:p-24 text-center max-w-7xl mx-auto relative overflow-hidden">
                    {/* Abstract subtle background shapes */}
                    <div className="absolute top-0 right-0 w-[400px] h-[400px] bg-light-blue rounded-full blur-[100px] opacity-60" />
                    <div className="absolute bottom-0 left-0 w-[300px] h-[300px] bg-light-green rounded-full blur-[100px] opacity-60" />

                    <div className="relative z-10 max-w-3xl mx-auto">
                        <div className="inline-flex items-center gap-2 bg-light-blue text-ocean-blue px-5 py-2 rounded-full text-sm font-bold tracking-widest uppercase mb-8 border border-sky-blue/20">
                            <TrendingUp className="w-4 h-4" /> Market Data & Analysis
                        </div>
                        <h1 className="text-4xl md:text-6xl font-bold mb-6 text-deep-forest leading-tight">
                            An Expanding <span className="text-ocean-blue">Blue Economy</span>
                        </h1>
                        <p className="text-xl text-slate font-medium leading-relaxed">
                            Understand the economic forces accelerating the viability of sustainable aquaculture. Seaweed is rapidly becoming a cornerstone biological asset.
                        </p>
                    </div>
                </div>
            </section>

            {/* Main Stats Grid */}
            <section className="py-24 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                <div className="grid md:grid-cols-2 gap-6">
                    <div className="glass-card p-12 flex flex-col justify-center items-center text-center group">
                        <div className="w-20 h-20 bg-light-blue rounded-3xl flex items-center justify-center mb-8 border border-sky-blue/20">
                            <PieChart className="w-10 h-10 text-ocean-blue group-hover:scale-110 transition-transform" />
                        </div>
                        <h3 className="text-6xl font-black text-deep-forest mb-4">
                            <CountUpNumber end={26.6} prefix="$" suffix="B" decimals={1} />
                        </h3>
                        <p className="text-xl font-bold text-ocean-blue mb-2">Global Seaweed Market Projection</p>
                        <p className="text-slate">Expected global market size generated by raw seaweed biomass processing by the year 2032.</p>
                    </div>

                    <div className="bg-deep-forest text-white p-12 rounded-[2.5rem] shadow-xl flex flex-col justify-center items-center text-center group hover:-translate-y-2 transition-transform relative overflow-hidden">
                        <div className="absolute bottom-0 left-0 w-full h-1/2 bg-gradient-to-t from-kelp-green/20 to-transparent" />
                        <div className="w-20 h-20 bg-white/10 backdrop-blur-md rounded-3xl flex items-center justify-center mb-8 border border-white/20 relative z-10">
                            <TrendingUp className="w-10 h-10 text-kelp-green group-hover:text-white transition-colors" />
                        </div>
                        <h3 className="text-6xl font-black text-white mb-4 relative z-10">
                            <CountUpNumber end={12.36} suffix="%" decimals={2} />
                        </h3>
                        <p className="text-xl font-bold text-kelp-green mb-2 relative z-10">Compound Annual Growth Rate</p>
                        <p className="text-white/70 relative z-10">One of the fastest accelerating sub-sectors in agriculture and food innovation worldwide.</p>
                    </div>
                </div>
            </section>

            {/* Secondary Data Offset */}
            <section className="pb-24 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                <div className="mb-12">
                    <span className="text-kelp-green font-bold uppercase tracking-widest text-sm mb-4 block">• Revenue Streams</span>
                    <h2 className="text-3xl font-bold text-deep-forest">Market Drivers</h2>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
                    {[
                        { title: "Fertilizer & Feed", desc: "Raw kelp biomass is highly sought after as a rich organic fertilizer and an additive in livestock feed." },
                        { title: "Carbon Credits", desc: "Verified carbon sequestered by kelp farms introduces a powerful secondary market revenue stream." },
                        { title: "Food & Cosmetics", desc: "Refined seaweed extracts (agar, carrageenan) are essential stabilizers in global consumer supply chains." }
                    ].map((item, i) => (
                        <div key={i} className="glass-card p-8 hover:shadow-xl hover:border-kelp-green/50 transition-all group">
                            <h4 className="text-xl font-bold mb-4 text-deep-forest flex items-center gap-3">
                                <span className="w-8 h-8 rounded-full bg-light-green text-kelp-green flex items-center justify-center text-sm">{i + 1}</span>
                                {item.title}
                            </h4>
                            <p className="text-slate leading-relaxed">{item.desc}</p>
                        </div>
                    ))}
                </div>
            </section>

            {/* Bottom CTA Block */}
            <section className="bg-deep-forest text-white py-24 px-4 text-center mt-12 rounded-t-[3rem] relative overflow-hidden">
                <div className="absolute inset-0 opacity-10">
                    <div className="absolute top-0 right-0 w-[400px] h-[400px] bg-sky-blue rounded-full blur-[120px]" />
                </div>
                <div className="max-w-3xl mx-auto relative z-10">
                    <h2 className="text-4xl font-bold mb-6">Investigate the Data</h2>
                    <p className="text-white/80 text-lg mb-10 max-w-xl mx-auto">
                        Our market analyses are based on rigorous economic studies and peer-reviewed marine biology research. Let's discuss the numbers.
                    </p>
                    <div className="flex flex-col sm:flex-row gap-4 justify-center">
                        <Link href="https://cal.com/aquagrid" target="_blank" className="bg-sky-blue text-deep-forest hover:bg-white px-8 py-4 rounded-full font-bold transition-all shadow-xl hover:-translate-y-1 text-lg">
                            Book a Strategy Call
                        </Link>
                        <Link href="/contact" className="bg-white/10 border border-white/20 text-white hover:bg-white/20 px-8 py-4 rounded-full font-bold transition-all text-lg hidden sm:flex items-center justify-center">
                            Send an Inquiry
                        </Link>
                    </div>
                </div>
            </section>

        </div>
    );
}
